### ISSUE TITLE
Bloom Filters

### ISSUE THREAD

**Issue by marvin-j97** [marvin-j97/lsm-tree#12]
Need a bloom (or XOR or ribbon or cuckoo) filter, that:

1) can be restored from disk/raw bytes

This is obvious. On recovery, load all bloom filters back into memory from disk. So the bloom filter needs to be able to give us its internal bytes and needs a constructor to recreate it from raw bytes.

2) can be resized while writing to it

RocksDB used to store a bloom filter per data block, so filter construction is simple. However, its read path is much worse because you need to travel through the SST file. The new full filter format just stores one big bloom filter per SST file. That requires much more memory when flushing and compacting because all keys or hashes need to be buffered until the SST is written because the number of items is unknown until everything is written. Then the bloom filter needs to be built from the buffer.

Using a scalable filter may solve this memory issue.

3) Also...

[M O N K E Y](https://stratos.seas.harvard.edu/files/stratos/files/monkeykeyvaluestore.pdf) may maximize efficiency for a given amount of memory: http://daslab.seas.harvard.edu/monkey/.

**Comment by arthurprs** [comment]
If you can reasonably guess the number of keys, a resizable filter might do the trick. Having written https://github.com/arthurprs/qfilter, I can tell that each AMQ-Filter has its own set of tradeoffs, specially the resizeable ones.

Take qfilter for example, it can only assume power of two sizes, it can resize by doubling in size and dropping one bit of fingerprint (doubling the false positive ratio). So it's still somewhat important to guess the number of keys correctly. If you underestimate, the filter might still double, but you get twice the desired false-positive rate. If you underestimate by a huge margin, then the filter will fail to resize. If you overestimate, then you end up with a filter that has less false positives.

**Comment by marvin-j97** [comment]
> If you can reasonably guess the number of keys, a resizable filter might do the trick. Having written https://github.com/arthurprs/qfilter, I can tell that each AMQ-Filter has its own set of tradeoffs, specially the resizeable ones.
> 
> Take qfilter for example, it can only assume power of two sizes, it can resize by doubling in size and dropping one bit of fingerprint (doubling the false positive ratio). So it's still somewhat important to guess the number of keys correctly. If you underestimate, the filter might still double, but you get twice the desired false-positive rate. If you underestimate by a huge margin, then the filter will fail to resize. If you overestimate, then you end up with a filter that has less false positives.
> 
> That said, IMO buffering the hashes doesn't seem that bad for the usual sstable sizes.

Hi, thanks for the message.
So far I've also been eyeing on just implementing buffering and a standard bloom filter. If I can buffer the hashes (not the user keys themselves), and one uses seven hash functions, that's 7 U32s per user key. So for 100 M items (which is an absolutely giant SSTable), that should add up to around 2.8 GB of temporary memory usage. So far, I'm not sure if there's a Rust implementation that can give me the hash without having to construct the actual filter, so I might have to roll my own.

There's also InfiniFilter (https://dl.acm.org/doi/10.1145/3589285), but there's no Rust implementation for it and I don't know which tradeoffs it would have compared to a standard Bloom filter. Also the filter needs to be stored to disk as raw bytes, which is easiest with a standard bloom filter.

Also RocksDB has implemented Ribbon filters, which can save a lot of space, but needs even more temporary memory.

**Comment by arthurprs** [comment]
> If I can buffer the hashes (not the user keys themselves), and one uses seven hash functions, that's 7 U32s per user key.

You can get away with 2 well sized hashes (2x 64bit) and use [double hashing](https://en.wikipedia.org/wiki/Double_hashing#Enhanced_double_hashing) to get the rest. I haven't checked what strategy rocksdb uses, but I'd not be surprised if it's exactly that.

> There's also InfiniFilter (https://dl.acm.org/doi/10.1145/3589285), but there's no Rust implementation for it and I don't know which tradeoffs it would have compared to a standard Bloom filter. Also the filter needs to be stored to disk as raw bytes, which is easiest with a standard bloom filter.

InfiniFilter is an extension of the data structure that qfilter implements (counting quotient filter) but it stores 1 more metadata bit per entry. It's a trade-off to get significantly better resizing behavior, but otherwise that metadata bit could have been an additional fingerprint bit. As in, a perfectly sized quotient filter will have twice less false positives than a similarly sized InifiFilter.

**Comment by marvin-j97** [comment]
> You can get away with 2 well sized hashes (2x 64bit) and use [double hashing](https://en.wikipedia.org/wiki/Double_hashing#Enhanced_double_hashing) to get the rest. I haven't checked what strategy rocksdb uses, but I'd not be surprised if it's exactly that.

Good to know, I can't say that I'm really that experienced with probabilistic filters.
